// Home airport → ISO-3166-2 region, for regional public holidays.
//
// SERVER-ONLY: both JSONs total ~180 KB and are listed in
// client-bundle.test.ts. The client only ever sees the one region name the
// API response carries.
//
// Data from OurAirports (public domain), regenerated by
// scripts/gen-airport-regions.mjs. The region vocabulary matches Nager.Date's
// `counties` arrays (verified for ES/DE/AT/IT when this landed; the one known
// disagreement, Brandenburg, is remapped in the generator).
import airportRegions from "@/lib/airport-regions.json";
import regionNames from "@/lib/region-names.json";

const REGIONS = airportRegions as Record<string, string>;
const NAMES = regionNames as Record<string, string>;

export function regionOfAirport(iata: string): string | null {
  return REGIONS[iata.toUpperCase()] ?? null;
}

/** Human name for an ISO-3166-2 code ("ES-CT" → "Catalonia"); the code itself
 *  when the table has no name, so a label can always be printed. */
export function regionName(code: string): string {
  return NAMES[code] ?? code;
}

// The inference is deliberately conservative: it answers only when every home
// airport agrees on one region inside the home country. BCN+MAD (two regions)
// and BSL (French parcel, Swiss/German users) both come back null, which means
// "national holidays only until the user says otherwise" — the app must never
// claim a day off the traveller doesn't actually have, and a wrong region
// would do exactly that.
export function inferHomeRegion(
  origins: string[],
  homeCountry: string
): string | null {
  let region: string | null = null;
  for (const code of origins) {
    const r = regionOfAirport(code);
    if (!r || !r.startsWith(`${homeCountry.toUpperCase()}-`)) return null;
    if (region === null) region = r;
    else if (region !== r) return null;
  }
  return region;
}
